### ISSUE TITLE
日本語版 (ja)

### ISSUE THREAD

**Issue by koriym** [ray-di/ray-di.github.io#4]
Related: #19 

- [x] Installation
- [x] Overview
- [x] Motivation
- [x] Getting Started
- [x] Mental Model
- [x] Scopes
- [x] Bindings
- [x] ・Linked Bindings
- [x] ・Binding Attributes
- [x] ・Instance Bindings
- [x] ・Provider Bindings
- [x] ・Untargeted Bindings
- [x] ・Constructor Bindings
- [x] ・Built-in Bindings
- [x] ・Multibindings
- [x] ・Contextual Bindings
- [x] ・Null Object Bindings
- [x] Injections
- [x] ・Injecting Providers
- [x] Object Life Cycle
- [x] AOP
- [x] Graphing Applications
- [x] Integration
- [x] Backward Compatibility

Best Practice (bp/)

- [x] AvoidConditionalLogicInModules.md
- [x] AvoidStaticState.md
- [ ] CyclicDependencies.md
- [x] DocumentPublicBindings.md
- [ ] DontReuseAnnotations.md
- [x] InjectOnlyDirectDependencies.md
- [x] InjectingTheInjector.md
- [x] MinimizeMutability.md
- [ ] ModulesShouldBeFastAndSideEffectFree.md
- [x] OrganizeModulesByFeature.md

チェックが付いてないものが手がついていないものです。取り掛かるときにコメントしてチェックをリクエストします。

## 翻訳手順

- １つ目のcommitはDeepLで自動翻訳
- ２つ目以降のcommitでヒトが校正

参考　https://github.com/ray-di/ray-di.github.io/pull/10

追記：#13　で英語ページを/jaにコピーしてて、JavaのコードはPHPに書き直されています。

**注意** 英語をコピーしてそのままDeeplで翻訳すると英文の改行が含まれてて訳がおかしくなり直します。ウインドウサイズを横に伸ばしたりして確認して不要な改行を削除して、カット＆ペーストでもう一度全文を翻訳すると良いです。

**Comment by komtaki** [comment]
Bindingsを翻訳してみようと思います。:+1:

**Comment by 77web** [comment]
Injectionsやります！！

**Comment by orifuji** [comment]
初めまして！

素敵なドキュメントだなと思ったのでcontributeさせてください
（新規issueを作るほどのことでもなさそうなのと、一応翻訳PJの範疇の内容だと判断しましたので、こちらに着手宣言いたします）

用件：
一点、英・日双方に共通する誤りを見つけたので共有、またPRを作成しておきます

問題：
PHPへと置換済みのコード例のなかに、classに対するアクセス修飾子が使用されている箇所があります
たぶん、Guiceドキュメントに書かれていたJavaコードの名残かなと思います

対応：
一応現時点でphp化されていそうな箇所についてはpublicを外しておきます

ex:

Motivation／モチベーション中のコード例
```php
public class RealBillingService implements BillingServiceInterface
```

**Comment by orifuji** [comment]
Constructor Bindingsやります

**Comment by koriym** [comment]
Constructor Bindingsはアノテーション/アトリビュートがつけれないサードパーティのコードのためで他の束縛と性格が違います。純粋なGuiceのDIからは離れてしまうのは申し訳ないところですが、どのように解決したかという視点で見てもらうと！

**Comment by koriym** [comment]
@orifuji また元々は日本語なのでこちらを見てもらうと
https://github.com/ray-di/Ray.Di/blob/2.13.3/README.ja.md#コンストラクタ束縛

**Comment by orifuji** [comment]
@koriym 
あ、なるほど！　本体READMEからの逆輸入なんですね（英文Doc側ばかり見ていて気づきませんでした）

となると翻訳というよりほぼ移植になってしまうかもしれませんが、着手します！

**Comment by komtaki** [comment]
Linked Bindingsをやります 👍

**Comment by orifuji** [comment]
(Constructor Bindingsで頂いたレビューも踏まえつつ、）今度はNull Object Bindingsをやります！

**Comment by momospnr** [comment]
@koriym 
Instance Bindingsをやります！

**Comment by koriym** [comment]
コントリビュートしている人の"クレジットのために"Assigneesに設定しました。You guys are great!

**Comment by jingu** [comment]
Provider Bindings やりますね。

**Comment by apple-x-co** [comment]
@koriym bp/MinimizeMutability をやってみます🐣

**Comment by apple-x-co** [comment]
bp/InjectOnlyDirectDependencies をやります🐣

**Comment by koriym** [comment]
AvoidStaticStateやります。

**Comment by apple-x-co** [comment]
bp/InjectingTheInjector をやります🐥

**Comment by koriym** [comment]
bp/CyclicDependenciesやります✋

**Comment by apple-x-co** [comment]
bp/DontReuseAnnotations やります🐰

**Comment by apple-x-co** [comment]
bp/OrganizeModulesByFeature やります🐞

**Comment by apple-x-co** [comment]
bp/ModulesShouldBeFastAndSideEffectFree やります🐛

**Comment by koriym** [comment]
@apple-x-co コンプリートまでカウントダウンですね！

**Comment by apple-x-co** [comment]
> @apple-x-co コンプリートまでカウントダウンですね！

そうですね!!
このベストプラクティスは、本当に重要だも思っているので、完成間近で嬉しいです。
このページが終われば、既存ページは完了ですね。

あとは、用語の統一のために、全ページ見たほうが良い気もしてます。

**Comment by koriym** [comment]
* [ ] 用語の統一
* [ ] タイトル

いいですね。
